# Generated by Django 3.1.7 on 2021-05-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='initial_balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_bal', models.IntegerField()),
            ],
        ),
    ]
